[theme]
base="dark"
primaryColor="#7F00FF"

[server]
#port = 8080
#address = "0.0.0.0"
enableStaticServing = true

[runner]
magicEnabled = false

[browser]
#serverAddress = "0.0.0.0"
#serverPort = 8080
